name: Destroy AWS Resources
run-name: ${{ github.actor }} has triggered a destroy pipeline

on:
  workflow_dispatch:  # Manual trigger

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy-infra:
    name: terraform-destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform-VPC

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan
        working-directory: ./Terraform-VPC

      - name: Terraform Apply Destroy
        run: terraform apply -auto-approve tfplan
        working-directory: ./Terraform-VPC
